# fly.toml app configuration file generated for notes-blue-haze-2801 on 2025-05-10T00:36:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notes-blue-haze-2801'
primary_region = 'lhr'

[build]

[env]
  PORT = "3001" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
