POST http://127.0.0.1:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2ODRjMDcwM2U0MTg0OTIzYjczYWJlOWUiLCJpYXQiOjE3NDk4MTMwMTMsImV4cCI6MTc0OTgxNjYxM30.fo8wG8btoDpQJ8Zu6c-xsn2Ibo6CuaOneRnlsPch7xs

{
    "title": "New Blog Post fromadmin",
    "author": "New admin",
    "url": "https://new-url-admin.com",
    "likes": 5
}