POST http://127.0.0.1:3000/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cI6IkpXVCJ9.eyJ1c2VybmtZSI6InJvb3QxIiwiaWQiOiI2ODJlNWY1M2NjOTkyYWJjZDFiN2VlOTkiLCJpYXQiOjE3NDgwNDMyMTMsImV4cCI6MTc0ODA0NjgxM30.HcMngitPK8cXfKZSrdC4mmRtt1x_e9uR4MIiD-5h2Ac

{
    "title": "New Blog Post",
    "author": "New Author",
    "url": "https://new-url.com",
    "likes": 5
}