DELETE http://localhost:3000/api/blogs/68310c9a346445ae6d7f26f4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QIiwiaWQiOiI2ODJlNWY1M2NjOTkyYJjZDFiN2VlOTkiLCJpYXiOjE3NDgwNDMyMTMsImV4cCI6MTc0ODA0NjgxM30.HcMngitPK8cXfKZSrdC4mmRtt1x_e9uR4MIiD-5h2Ac